#!/usr/bin/env python3
"""
Sample script for synthesizing text to speech.
"""

from cli import run_cli

def main():
    text = "This is a sample voiceover generated by the offline TTS tool."
    args = ['synth', '--text', text, '--voice', 'narrator', '--out', 'sample_output.mp3']
    run_cli(args)
    print("Sample synthesis completed.")

if __name__ == "__main__":
    main()